### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [akerpelm/infinote#2]
- [x] You only need an email and a password, not a username (that is all evernote asks for on signup) 

This schema looks good! Let me know if you have any questions

**Comment by akerpelm** [comment]
Thank you. I added the username row to the table because upon login you have the option to set a username if you'd like. I figured this would be a good functionality to implement, and would not require it upon login (or in constraints/validations). I will write a note under the table to make this more clear. Let me know what you think!

**Comment by PLUCS2** [comment]
That looks perfect - thank you for that clarification Alex!
